"""Remove auth fields from Empleado

Revision ID: f5c232ee257e
Revises: e4db4f11fbf6
Create Date: 2025-12-16 00:28:08.996362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c232ee257e'
down_revision: Union[str, None] = 'e4db4f11fbf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_empleados_email', table_name='empleados')
    op.drop_column('empleados', 'email')
    op.drop_column('empleados', 'is_active')
    op.drop_column('empleados', 'hashed_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('hashed_password', sa.VARCHAR(), nullable=True))
    op.add_column('empleados', sa.Column('is_active', sa.BOOLEAN(), nullable=True))
    op.add_column('empleados', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.create_index('ix_empleados_email', 'empleados', ['email'], unique=1)
    # ### end Alembic commands ###
